Add NeoChat
matrix-org/matrix.to pull request #253
Opened 2021-12-25 21:53 UTC by CarlSchwan

2021-12-25 22:01 UTC, nicolasfella commented on src/open/clients/NeoChat.js
> +    get description() { return 'NeoChat is a Matrix convergent client fully integrated inside Plasma Mobile and Plasma Desktop, but it also works on many other platforms.'; }
```suggestion
    get description() { return 'NeoChat is a convergent, cross-platform Matrix client.'; }
```

2022-01-06 09:36 UTC, CarlSchwan commented
Friendly ping @bwindels :)

2022-05-12 19:05 UTC, CarlSchwan commented
Ping?

2022-05-17 12:52 UTC, thibaultamartin requested changes

2022-05-17 12:52 UTC, thibaultamartin commented on src/open/clients/NeoChat.js
> +    get platforms() { return [Platform.Linux, Platform.Windows, Platform.macOS, Platform.Android]; }
After talking with the maintainers, it seems there is no official release on other platforms than Linux. It probably doesn't make sense to advertise NeoChat on other platforms for now

2022-05-20 15:53 UTC, thibaultamartin approved these changes

2022-05-20 15:54 UTC, merged

2022-05-20 15:54 UTC, thibaultamartin commented
Thanks Carl!